travis:
  secure:
    BINSTAR_TOKEN: DVzPy0D/KX0vQL9iM6XGLGriUkzlKq80kx9zddmBVKsXOhrHe7lHYs2IhWDJ4Ji8m81mris8cj1mlGkxj50yro6xK53OUmw/tgygso5u8f6qv5Yz6fspedyEa2D8ATGu7Gb/4vty3IpvKMXRDlMmdbR1zQXB5WSuGMQfRcC88RWolNmMWWY8fcQrxI4vPfj0BVjfuyFa4oA7vUTykwQo5YKiRVSUKoDtrlj19QGtjVWbdJXUUD5NdWqHas9kl+IL38V/rN9F3FoOZQAsdz1DOe+yQ4tqGaOEXzgjhrSTneJ/Szlm+sMVfHM929R/XYKXBRsJhnLSd/4+nvesaU3gzJCtAILhRKnnWjaaTYO0fQzuTDMEGEOcdwN2uuv2fyy4cBGG/F2Z/LbpLuJm03a0hQXehMD0bW7D0mv99EWA3LZZC4n6hPbC6lpV2zend9age6eooW+yz1c1F+vmN0Wmdlb0SVwusPg4gtKEs6APRZZ38q+7ZOOCTfs/vw0eYAaR/5/xYi9XGP06Uhycfjg9gFbVdT6ThVF6suNcaChC2B6dy0U/bIQ1IIWWXet9pHo4wiFNzIaEyCzXwvsTo8o4IvXN71qrtxNyi6vL3cpuCRsC1T3riY7FH/LB1dju+Os9io26nV+qnDAnSKdh0i0W5CAJEMiH8Izn4J2xpSLbGpU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
