travis:
  secure:
    BINSTAR_TOKEN: eYMnlQZCxrh2TaH91vqDFMePUZm4R5uO5bKyTD/BbizFsdOaQMbh9hcmjg33svrEDFCIkIaAOQDOmS2rqS9tjBN/QFOOjedZk1+y1p2iFXJpilhmH6+7n/La3BpS/uJgNi5EWRYhjQpLL6Ty+pOAKWjdbk6ZgzK4DeTpv7nTNAfTch8z/T56CFSbDTG7Y4vnlRM0MTKPcPQxkzdFz3LnVI6Qag3QuYrvMpjCd7e6KETnbDlTyJFrvAId6GNQFvbjohjEKGYnFcBKsZIuOiBCbkcWweoDUCvSFGTlzzlt0MJn+KHt/HKQ2SStF9Tu1Q7RmEzQVDjT8Lt5lCq/ar+B+uvKfyPDByXtOAqJGHYeIQZRmWJUaUDIfhzOtweHKagCzCA9shCjOXKmM7nJDK8Jt+X7Jp3So933Mzoe3P0zEFj1GxLNapRvrmeyDBcMsp85hkz/sXemK4dp+xbkPEoHXY0fzY3spd3VxAkPcOD1wKjOxA8HGSoBs7FbBEb+WHI38SR+/UWnbJE1re90flSq4UtHW7pxUVb3+JSvxCNR4Ld6OJ4zMJn5arfMq4+3aHYta2wWyGQhK7c42DH8vVYtvFw6SK9bPAsKRRLfWYAJVGkFPJNd8xe+cfjYDWdd9mZR+4LNP25uFNAif+vN5AAzUy6WXYZZg7PviP/fL71nD9E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
